"""Frozen pre-registration for the Autonomous Alpha Lab holdout read.

Written after the 2022-2024 discovery grid and BEFORE the 2025 holdout was
read even once. The bar below is the brief's own VALIDATED_EDGE_CANDIDATE
requirement list, made mechanical so it cannot be softened after the fact.

Do not edit this file to fit a result. If a rule here turns out to be the
wrong rule, that is a finding to report, not a threshold to move.
"""
from __future__ import annotations

PREREGISTERED_AT = "2026-09-10"

# ---------------------------------------------------------------- the claim --

PRIMARY = {
    "method": "trend_anti_junk",
    "universe": "liquid_tradable",
    "list_size": 10,
    "horizon_days": 60,
    "rationale": (
        "Delivers the shape the brief asks for — a 5-15 name, manually tradable list — "
        "and every component was motivated by prior published TRAIN-ONLY evidence in this "
        "repo (the dd_from_high and volatility decile tables in ALPHA_RECONSTRUCTION_LAB, "
        "the 12-1 result in ALPHA_TOURNAMENT), not by searching this study's own grid."
    ),
}

SECONDARY = [
    {"method": "trend_anti_junk", "universe": "liquid_tradable", "list_size": 5, "horizon_days": 60},
    {"method": "trend_anti_junk", "universe": "liquid_tradable", "list_size": 15, "horizon_days": 60},
    {"method": "trend_anti_junk", "universe": "liquid_tradable", "list_size": 10, "horizon_days": 20},
    {"method": "composite_z", "universe": "liquid_tradable", "list_size": 10, "horizon_days": 60},
    {"method": "trend_anti_junk", "universe": "full_prior_work", "list_size": 10, "horizon_days": 60},
    {"method": "trend_anti_junk", "universe": "strict_tradable", "list_size": 10, "horizon_days": 60},
]

# Reported for contrast at every holdout cell; never candidates.
BASELINES = ("mom_12_1", "old_scanner_axis", "low_vol_control", "mom_12_1_style_neutral")

# ------------------------------------------------------------------ the bar --

BAR = {
    "holdout_selection_positive": "holdout selection vs same-date universe mean > 0",
    "non_overlapping_positive": "selection > 0 on non-overlapping windows in BOTH train and holdout",
    "mean_and_median_positive": "cohort mean AND median forward return > 0 in holdout",
    "beats_same_date_random": "holdout vs-random-same-date CI lower bound > 0",
    "beats_matched_random": "holdout vol x liquidity matched-random CI lower bound > 0",
    "date_clustered_ci_positive": "holdout date-clustered (portfolio) CI lower bound > 0",
    "ticker_clustered_ci_positive": "holdout ticker-clustered (typical name) CI lower bound > 0",
    "not_one_month": "leave-one-month-out selection stays > 0 in both splits",
    "not_one_ticker": "selection excluding the 5 most-represented tickers stays > 0 in both splits",
    "not_one_sector": "largest labelled sector share <= 40% of cohort episodes",
    "enough_observations": "holdout dates >= 40 and unique tickers across both splits >= 100",
    "no_lookahead": "every ranking input passes the forward-column deny-list",
}

# Verdict ladder — the brief's labels, and only these.
LADDER = (
    "REJECTED",
    "OVERFIT",
    "INCONCLUSIVE",
    "PROMISING_BUT_UNPROVEN",
    "PROVISIONAL_RESEARCH_CANDIDATE",
    "VALIDATED_EDGE_CANDIDATE",
)

# How the checks map onto the ladder.
VERDICT_RULES = {
    "VALIDATED_EDGE_CANDIDATE": "every check in BAR passes",
    "PROVISIONAL_RESEARCH_CANDIDATE": (
        "holdout selection positive, both clustered CIs positive, beats matched random, "
        "and no fragility check fails — but at least one of the remaining checks fails"
    ),
    "PROMISING_BUT_UNPROVEN": "holdout selection positive and beats matched random, but a clustered CI includes zero",
    "INCONCLUSIVE": "holdout selection positive but does not beat matched random, or CIs straddle zero both ways",
    "OVERFIT": "train selection clearly positive and holdout selection <= 0",
    "REJECTED": "selection <= 0 in both splits, or a CI clear of zero on the negative side",
}

# Multiple-testing acknowledgement, recorded before the read.
MULTIPLICITY = {
    "train_cells_scored": 288,
    "methods": 8,
    "list_sizes": 6,
    "horizons": 2,
    "universes": 3,
    "note": (
        "288 train cells were scored, so several will look good by chance. This is why the "
        "verdict rests on ONE pre-registered primary cell, why the bar demands an out-of-sample "
        "year plus two clusterings plus two control cohorts rather than a p-value, and why the "
        "secondary cells are reported as consistency checks and can never lift a verdict on their own."
    ),
}
